// Word pools for the display name auto-generated at signup. Kept as a .ts module,
// not JSON: the build only copies src/locales/*.json into dist, so a JSON data
// file anywhere else under src/ would be missing in production.

// Hong Kong and Taiwan place names, paired as `<place>的<nature>`.
export const DISPLAY_NAME_PLACES_ZH = [
  '中環', '金鐘', '灣仔', '銅鑼灣', '天后', '炮台山', '北角', '鰂魚涌', '太古', '西灣河', '筲箕灣', '柴灣', '杏花邨',
  '小西灣', '西環', '堅尼地', '石塘咀', '西營盤', '上環', '半山', '太平山', '山頂', '寶馬山', '薄扶林', '數碼港', '瀑布灣',
  '雞籠灣', '田灣', '香港仔', '鴨脷洲', '海怡', '黃竹坑', '壽臣山', '深水灣', '淺水灣', '中灣', '南灣', '赤柱', '舂坎角',
  '大潭', '石澳', '鶴咀', '尖沙咀', '尖東', '佐敦', '油麻地', '旺角', '太子', '大角咀', '深水埗', '長沙灣', '荔枝角',
  '美孚', '石硤尾', '白田', '又一村', '九龍塘', '樂富', '橫頭磡', '黃大仙', '鑽石山', '慈雲山', '彩虹', '牛池灣', '斧山',
  '九龍城', '土瓜灣', '馬頭圍', '馬頭角', '啟德', '紅磡', '何文田', '窩打老', '採石山', '昂船洲', '牛頭角', '九龍灣',
  '觀塘', '秀茂坪', '順天', '順安', '順利', '佐敦谷', '藍田', '油塘', '鯉魚門', '茶果嶺', '葵涌', '葵芳', '葵興',
  '大窩口', '荃灣', '青衣', '汀九', '深井', '青龍頭', '馬灣', '屯門', '三聖', '蝴蝶灣', '掃管笏', '大欖', '小欖',
  '藍地', '洪水橋', '元朗', '朗屏', '天水圍', '錦田', '八鄉', '石崗', '新田', '落馬洲', '米埔', '上水', '粉嶺',
  '聯和墟', '沙頭角', '打鼓嶺', '鹿頸', '谷埔', '荔枝窩', '烏蛟騰', '新娘潭', '大埔', '太和', '康樂園', '大尾篤', '白石角',
  '火炭', '沙田', '大圍', '馬鞍山', '烏溪沙', '恆安', '十四鄉', '泥涌', '西貢', '白沙灣', '蠔涌', '早禾坑', '大網仔',
  '北潭涌', '糧船灣', '橋咀島', '鹽田梓', '清水灣', '布袋澳', '大坳門', '將軍澳', '調景嶺', '坑口', '寶琳', '康城',
  '百勝角', '東涌', '赤鱲角', '機場', '大澳', '梅窩', '昂坪', '貝澳', '長沙', '塘福', '水口', '石碧', '愉景灣', '陰澳',
  '竹篙灣', '長洲', '坪洲', '南丫島', '榕樹灣', '索罟灣', '蒲台島', '東平洲', '塔門', '吉澳', '鴨洲', '果洲', '獅子山',
  '飛鵝山', '大帽山', '鳳凰山', '大東山', '龍脊', '筆架山', '慈沙古', '金山', '城門', '菠蘿壩', '針山', '草山', '猴塘溪',
  '浪茄', '大浪灣', '鹹田灣', '西灣', '東灣', '萬宜', '西門町', '大稻埕', '艋舺', '萬華', '公館', '士林', '北投',
  '陽明山', '內湖', '南港', '松山', '信義', '大安', '文山', '木柵', '景美', '貓空', '社子', '關渡', '天母', '劍潭',
  '圓山', '師大', '台大', '象山', '板橋', '新莊', '中和', '永和', '三重', '蘆洲', '汐止', '新店', '碧潭', '烏來',
  '鶯歌', '三峽', '樹林', '土城', '淡水', '八里', '三芝', '石門', '野柳', '萬里', '瑞芳', '九份', '金瓜石', '猴硐',
  '鼻頭角', '平溪', '十分', '菁桐', '雙溪', '貢寮', '福隆', '坪林', '深坑', '石碇', '基隆', '廟口', '暖暖', '七堵',
  '八斗子', '和平島', '桃園', '中壢', '平鎮', '八德', '大溪', '復興', '拉拉山', '楊梅', '蘆竹', '龜山', '大園', '竹圍',
  '觀音', '新屋', '永安', '新竹', '竹北', '竹東', '湖口', '新埔', '關西', '芎林', '橫山', '內灣', '北埔', '峨眉',
  '尖石', '司馬庫', '五峰', '苗栗', '頭份', '竹南', '三義', '南庄', '泰安', '大湖', '卓蘭', '銅鑼', '通霄', '白沙屯',
  '苑裡', '後龍', '西湖', '台中', '逢甲', '一中', '西屯', '北屯', '南屯', '豐原', '后里', '東勢', '新社', '谷關',
  '和平', '梨山', '武陵', '潭子', '大雅', '清水', '高美', '梧棲', '大甲', '沙鹿', '龍井', '大肚', '霧峰', '太平',
  '大里', '烏日', '彰化', '八卦山', '鹿港', '和美', '員林', '田尾', '溪湖', '田中', '二水', '芳苑', '王功', '南投',
  '草屯', '埔里', '日月潭', '清境', '合歡山', '溪頭', '杉林溪', '竹山', '集集', '水里', '車埕', '魚池', '國姓', '仁愛',
  '雲林', '斗六', '虎尾', '西螺', '北港', '古坑', '嘉義', '民雄', '阿里山', '奮起湖', '東石', '布袋', '台南', '安平',
  '中西區', '鹽水', '白河', '關子嶺', '麻豆', '玉井', '七股', '北門', '高雄', '駁二', '旗津', '西子灣', '左營', '美濃',
  '旗山', '岡山', '田寮', '屏東', '恆春', '墾丁', '小琉球', '花蓮',
] as const;

// International city names, paired as `<city>'s <nature>`.
export const DISPLAY_NAME_PLACES_EN = [
  'Tokyo', 'Kyoto', 'Osaka', 'Nagoya', 'Kobe', 'Fukuoka', 'Sapporo', 'Sendai',
  'Hiroshima', 'Nara', 'Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju',
  'Suwon', 'Ulsan', 'Jeju', 'Pohang', 'Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen',
  'Chengdu', 'Hangzhou', 'Wuhan', 'Nanjing', 'Tianjin', 'Xi\'an', 'Hong Kong', 'Taipei',
  'Tainan', 'Taichung', 'Kaohsiung', 'Hsinchu', 'Keelung', 'Chiayi', 'Hualien',
  'Taitung', 'Yilan', 'Bangkok', 'Phuket', 'Chiang Mai', 'Pattaya', 'Hanoi', 'Da Nang',
  'Hue', 'Saigon', 'Can Tho', 'Nha Trang', 'Jakarta', 'Surabaya', 'Bandung', 'Medan',
  'Semarang', 'Makassar', 'Denpasar', 'Manila', 'Cebu', 'Davao', 'Singapore',
  'KualaLumpu', 'Penang', 'Ipoh', 'Malacca', 'Kuching', 'Yangon', 'Mandalay',
  'Vientiane', 'Phnom Penh', 'Mumbai', 'Delhi', 'Bengaluru', 'Chennai', 'Kolkata',
  'Hyderabad', 'Pune', 'Ahmedabad', 'Jaipur', 'Surat', 'Dhaka', 'Chittagong', 'Colombo',
  'Kandy', 'Galle', 'Kathmandu', 'Pokhara', 'Thimphu', 'Male', 'Karachi', 'Lahore',
  'Islamabad', 'Dubai', 'Abu Dhabi', 'Doha', 'Riyadh', 'Jeddah', 'Mecca', 'Medina',
  'Muscat', 'London', 'Manchester', 'Liverpool', 'Birmingham', 'Leeds', 'Bristol',
  'Sheffield', 'Newcastle', 'Oxford', 'Cambridge', 'Edinburgh', 'Glasgow', 'Aberdeen',
  'Dundee', 'Belfast', 'Dublin', 'Cork', 'Galway', 'Limerick', 'Cardiff', 'Paris',
  'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellie',
  'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Toulon', 'Grenoble', 'Dijon', 'Angers',
  'Nimes', 'Brest', 'Le Mans', 'Amiens', 'Berlin', 'Hamburg', 'Munich', 'Cologne',
  'Frankfurt', 'Stuttgart', 'Dusseldorf', 'Leipzig', 'Dortmund', 'Essen', 'Bremen',
  'Dresden', 'Hannover', 'Nuremberg', 'Duisburg', 'Bochum', 'Wuppertal', 'Bielefeld',
  'Bonn', 'Munster', 'Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna',
  'Florence', 'Bari', 'Catania', 'Venice', 'Verona', 'Messina', 'Padua', 'Trieste',
  'Brescia', 'Parma', 'Taranto', 'Prato', 'Modena', 'Madrid', 'Barcelona', 'Valencia',
  'Seville', 'Zaragoza', 'Malaga', 'Murcia', 'Palma', 'Bilbao', 'Alicante', 'Cordoba',
  'Valladolid', 'Vigo', 'Gijon', 'Granada', 'Vitoria', 'Elche', 'Oviedo', 'Badalona',
  'Cartagena', 'Lisbon', 'Porto', 'Braga', 'Coimbra', 'Funchal', 'Vienna', 'Graz',
  'Linz', 'Salzburg', 'Innsbruck', 'Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern',
  'Lucerne', 'Lugano', 'Brussels', 'Antwerp', 'Ghent', 'Amsterdam', 'Rotterdam',
  'The Hague', 'Utrecht', 'Eindhoven', 'Stockholm', 'Gothenburg', 'Malmo', 'Uppsala',
  'Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Copenhagen', 'Aarhus', 'Odense',
  'Aalborg', 'Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Reykjavik',
  'Warsaw', 'Krakow', 'Lodz', 'Wroclaw', 'Poznan', 'Gdansk', 'New York', 'LosAngeles',
  'Chicago', 'Houston', 'Phoenix', 'Dallas', 'Austin', 'San Jose', 'Columbus',
  'Charlotte', 'Seattle', 'Denver', 'Boston', 'Detroit', 'Nashville', 'Portland',
  'Memphis', 'Las Vegas', 'Baltimore', 'Milwaukee', 'Atlanta', 'Miami', 'Raleigh',
  'Omaha', 'Oakland', 'Tulsa', 'Cleveland', 'Wichita', 'Arlington', 'Toronto',
  'Montreal', 'Calgary', 'Ottawa', 'Edmonton', 'Winnipeg', 'Vancouver', 'Brampton',
  'Hamilton', 'Quebec', 'Surrey', 'Laval', 'Halifax', 'Markham', 'Vaughan', 'Gatineau',
  'Windsor', 'Kitchener', 'Burnaby', 'MexicoCity', 'Tijuana', 'Ecatepec', 'Leon',
  'Puebla', 'Juarez', 'Guadalajar', 'Zapopan', 'Monterrey', 'Merida', 'Cancun',
  'Toluca', 'Chihuahua', 'Saltillo', 'Hermosillo', 'Culiacan', 'Veracruz', 'Irapuato',
  'Mazatlan', 'Oaxaca', 'Bogota', 'Medellin', 'Cali', 'Barranquil', 'Lima', 'Arequipa',
  'Trujillo', 'Chiclayo', 'Cusco', 'Santiago', 'Valparaiso', 'Concepcion', 'La Serena',
  'Antofagas', 'BuenosAire', 'Rosario', 'Mendoza', 'La Plata', 'Cairo', 'Alexandria',
  'Giza', 'Luxor', 'Aswan', 'Lagos', 'Kano', 'Ibadan', 'Abuja', 'Accra', 'Kumasi',
  'Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'AddisAbaba', 'Dire Dawa', 'Casablanca',
  'Rabat', 'Fez', 'Marrakesh', 'Tangier', 'Agadir', 'Tunis', 'Sfax', 'Sousse',
  'Algiers', 'Oran', 'Constantin', 'Dakar', 'Luanda', 'Maputo', 'Harare', 'Bulawayo',
  'Lusaka', 'Kigali', 'Kampala', 'DarEsSalam', 'Dodoma', 'Zanzibar', 'Cape Town',
  'Durban', 'Pretoria', 'Gqeberha', 'Bloemfont', 'Sydney', 'Melbourne', 'Brisbane',
  'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Hobart', 'Darwin', 'Auckland',
  'Wellington', 'Christchur', 'Tauranga', 'Athens', 'Thessalon', 'Prague', 'Brno',
  'Ostrava',
] as const;

// Animals and nature words for the Chinese pool. Not index-aligned with the
// English pool: the two locales draw independently.
export const DISPLAY_NAME_NATURE_ZH = [
  '獅子', '大象', '長頸鹿', '企鵝', '大熊貓', '藍鯨', '獵豹', '北極熊', '袋鼠', '海豚', '斑馬', '樹懶', '老鷹', '野狼',
  '駱駝', '狐狸', '變色龍', '海龜', '犀牛', '黑猩猩', '浣熊', '刺猬', '水獺', '鴨嘴獸', '穿山甲', '禿鷹', '貓頭鷹',
  '啄木鳥', '火烈鳥', '孔雀', '蜂鳥', '翠鳥', '虎鯨', '抹香鯨', '大白鯊', '魟魚', '海獅', '海象', '儒艮', '章魚',
  '烏賊', '水母', '樹蛙', '蠑螈', '科莫多', '響尾蛇', '眼鏡蛇', '獨角仙', '螢火蟲', '螳螂', '無尾熊', '河馬', '羚羊',
  '馴鹿', '犛牛', '狐獴', '豪豬', '松鼠', '土撥鼠', '負鼠', '食蟻獸', '犰狳', '羊駝', '美洲豹', '雪豹', '鬣狗', '狒狒',
  '長臂猿', '金絲猴', '環尾狐', '鵜鶘', '海鷗', '信天翁', '丹頂鶴', '喜鵲', '烏鴉', '鸚鵡', '麻雀', '燕子', '鸕鶿',
  '鯨鯊', '雙頭鯊', '電鰻', '小丑魚', '海馬', '旗魚', '翻車魚', '飛魚', '寄居蟹', '龍蝦', '珊瑚', '海膽', '海參',
  '鱷魚', '綠鬣蜥', '壁虎', '蟾蜍', '蜻蜓', '蝴蝶', '蜜蜂', '蜜獾', '雲豹', '美洲獅', '棕熊', '黑熊', '馬來熊', '麝牛',
  '瞪羚', '斑鬣狗', '藪貓', '獰貓', '兔猻', '樹袋熊', '針鼴', '袋熊', '袋獾', '狐蝠', '果蝠', '倉鼠', '天竺鼠', '水豚',
  '栗鼠', '海獺', '貂', '鼬', '獾', '獴', '麝香貓', '白鸛', '黑天鵝', '白天鵝', '鴛鴦', '綠頭鴨', '八哥', '畫眉',
  '百靈', '金絲雀', '蒼鷹', '隼', '鴯鶓', '鴕鳥', '奇異鳥', '藍腳鰹', '軍艦鳥', '蝠魟', '獅子魚', '盲鰻', '錦鯉',
  '金魚', '鬥魚', '極光', '彩虹', '日蝕', '月蝕', '閃電', '龍捲風', '地震', '海嘯', '流星雨', '潮汐', '晨霧', '冰雹',
  '暴風雪', '晚霞', '沙塵暴', '水龍捲', '霜凍', '露水', '霧淞', '暴雨', '颱風', '颶風', '乾旱', '雷暴', '寒潮', '熱浪',
  '結冰', '融雪', '雪崩', '山崩', '土石流', '日暈', '月暈', '幻日', '綠閃光', '藍眼淚', '赤潮', '火山煙', '熔岩流',
  '地熱泉', '間歇泉', '落雷', '靜電', '湧浪', '漩渦', '逆溫', '焚風', '季風', '鋒面', '氣旋',
] as const;

// Animals and nature words for the English pool.
export const DISPLAY_NAME_NATURE_EN = [
  'Lion', 'Elephant', 'Giraffe', 'Penguin', 'Panda', 'Whale', 'Cheetah', 'Polar Bear',
  'Kangaroo', 'Dolphin', 'Zebra', 'Sloth', 'Eagle', 'Wolf', 'Camel', 'Fox', 'Chameleon',
  'Turtle', 'Rhino', 'Chimp', 'Raccoon', 'Hedgehog', 'Otter', 'Platypus', 'Pangolin',
  'Vulture', 'Owl', 'Woodpecker', 'Flamingo', 'Peacock', 'Humming', 'Kingfisher',
  'Orca', 'SpermWhale', 'Shark', 'Stingray', 'Sea Lion', 'Walrus', 'Dugong', 'Octopus',
  'Squid', 'Jellyfish', 'Tree Frog', 'Salamander', 'Dragon', 'Snake', 'Cobra', 'Beetle',
  'Firefly', 'Mantis', 'Koala', 'Hippo', 'Antelope', 'Reindeer', 'Yak', 'Meerkat',
  'Porcupine', 'Squirrel', 'Marmot', 'Opossum', 'Anteater', 'Armadillo', 'Alpaca',
  'Jaguar', 'SnowLeop', 'Hyena', 'Baboon', 'Gibbon', 'Monkey', 'Lemur', 'Pelican',
  'Seagull', 'Albatross', 'Crane', 'Magpie', 'Crow', 'Parrot', 'Sparrow', 'Swallow',
  'Cormorant', 'WhaleShark', 'Hammerhead', 'Electric', 'Clownfish', 'Seahorse',
  'Sailfish', 'Sunfish', 'FlyingFish', 'Crab', 'Lobster', 'Coral', 'Sea Urchin',
  'Cucumber', 'Crocodile', 'Iguana', 'Gecko', 'Toad', 'Dragonfly', 'Butterfly', 'Bee',
  'HoneyBadg', 'CloudLeop', 'Cougar', 'Brown Bear', 'Black Bear', 'Sun Bear', 'Muskox',
  'Gazelle', 'Serval', 'Caracal', 'Pallas Cat', 'Echidna', 'Wombat', 'Devil', 'Fox Bat',
  'Fruit Bat', 'Hamster', 'Guinea Pig', 'Capybara', 'Chinchilla', 'Sea Otter', 'Marten',
  'Weasel', 'Badger', 'Mongoose', 'Civet', 'Stork', 'Black Swan', 'Mute Swan', 'Duck',
  'Mallard', 'Myna', 'Thrush', 'Lark', 'Canary', 'Goshawk', 'Falcon', 'Emu', 'Ostrich',
  'Kiwi', 'Booby', 'Frigate', 'Manta Ray', 'Lionfish', 'Hagfish', 'Koi', 'Goldfish',
  'Betta', 'Aurora', 'Rainbow', 'Eclipse', 'MoonEclips', 'Lightning', 'Tornado',
  'Earthquake', 'Tsunami', 'Meteors', 'Tide', 'Mist', 'Hail', 'Blizzard', 'Sunset',
  'Sandstorm', 'Spout', 'Frost', 'Dew', 'Rime', 'Rain', 'Typhoon', 'Hurricane',
  'Drought', 'Thunder', 'Cold Wave', 'Heat Wave', 'Freezing', 'Snowmelt', 'Avalanche',
  'Landslide', 'Mudflow', 'Solar Halo', 'Lunar Halo', 'Sun Dog', 'GreenFlash',
  'SeaSparkle', 'Red Tide', 'Volcano', 'Lava Flow', 'Hot Spring', 'Geyser',
  'CloudStrik', 'Static', 'Swell', 'Whirlpool', 'Inversion', 'Foehn', 'Monsoon',
  'Front', 'Cyclone',
] as const;
