module.exports = {
  FIRESTORE_USER_ROOT: process.env.FIRESTORE_USER_ROOT,
  FIRESTORE_USER_AUTH_ROOT: process.env.FIRESTORE_USER_AUTH_ROOT,
  FIRESTORE_TX_ROOT: process.env.FIRESTORE_TX_ROOT,
  FIRESTORE_IAP_ROOT: process.env.FIRESTORE_IAP_ROOT,
  FIRESTORE_PAYOUT_ROOT: process.env.FIRESTORE_PAYOUT_ROOT,
  FIRESTORE_MISSION_ROOT: process.env.FIRESTORE_MISSION_ROOT,
  FIRESTORE_CONFIG_ROOT: process.env.FIRESTORE_CONFIG_ROOT,
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
};
