const config = {};

config.FIRESTORE_USER_ROOT = process.env.FIRESTORE_USER_ROOT;
config.FIRESTORE_USER_AUTH_ROOT = process.env.FIRESTORE_USER_AUTH_ROOT;
config.FIRESTORE_SUBSCRIPTION_USER_ROOT = process.env.FIRESTORE_SUBSCRIPTION_USER_ROOT;
config.FIRESTORE_TX_ROOT = process.env.FIRESTORE_TX_ROOT;
config.FIRESTORE_IAP_ROOT = process.env.FIRESTORE_IAP_ROOT;
config.FIRESTORE_PAYOUT_ROOT = process.env.FIRESTORE_PAYOUT_ROOT;
config.FIRESTORE_MISSION_ROOT = process.env.FIRESTORE_MISSION_ROOT;
config.FIRESTORE_CONFIG_ROOT = process.env.FIRESTORE_CONFIG_ROOT;
config.FIRESTORE_COUPON_ROOT = process.env.FIRESTORE_COUPON_ROOT;
config.FIRESTORE_LIKER_NFT_ROOT = process.env.FIRESTORE_LIKER_NFT_ROOT;
config.FIRESTORE_NFT_SUBSCRIPTION_USER_ROOT = process.env.FIRESTORE_NFT_SUBSCRIPTION_USER_ROOT;
config.FIRESTORE_NFT_FREE_MINT_TX_ROOT = process.env.FIRESTORE_NFT_FREE_MINT_TX_ROOT;
config.FIRESTORE_LIKER_NFT_BOOK_CART_ROOT = process.env.FIRESTORE_LIKER_NFT_BOOK_CART_ROOT;
config.FIRESTORE_LIKER_NFT_BOOK_ROOT = process.env.FIRESTORE_LIKER_NFT_BOOK_ROOT;
config.FIRESTORE_LIKER_NFT_BOOK_USER_ROOT = process.env.FIRESTORE_LIKER_NFT_BOOK_USER_ROOT;
config.FIRESTORE_LIKER_PLUS_GIFT_CART_ROOT = process.env.FIRESTORE_LIKER_PLUS_GIFT_CART_ROOT;
config.FIRESTORE_OAUTH_CLIENT_ROOT = process.env.FIRESTORE_OAUTH_CLIENT_ROOT;
config.FIRESTORE_ISCN_INFO_ROOT = process.env.FIRESTORE_ISCN_INFO_ROOT;
config.FIRESTORE_ISCN_ARWEAVE_TX_ROOT = process.env.FIRESTORE_ISCN_ARWEAVE_TX_ROOT;
config.FIRESTORE_SUPERLIKE_USER_ROOT = process.env.FIRESTORE_SUPERLIKE_USER_ROOT;
config.FIRESTORE_LIKE_URL_ROOT = process.env.FIRESTORE_LIKE_URL_ROOT;
config.FIRESTORE_ISCN_LIKER_URL_ROOT = process.env.FIRESTORE_ISCN_LIKER_URL_ROOT;
config.FIREBASE_STORAGE_BUCKET = process.env.FIREBASE_STORAGE_BUCKET;

config.COSMOS_LCD_INDEXER_ENDPOINT = 'https://node.testnet.like.co';
config.COSMOS_LCD_ENDPOINT = 'https://node.testnet.like.co';
config.COSMOS_RPC_ENDPOINT = 'https://node.testnet.like.co/rpc/';
config.COSMOS_SIGNING_RPC_ENDPOINT = 'https://node.testnet.like.co/rpc/';
config.COSMOS_CHAIN_ID = 'likecoin-public-testnet-5';
config.COSMOS_DENOM = 'nanoekil';
config.NFT_RPC_ENDPOINT = 'https://node.testnet.like.co/rpc/';
config.NFT_SIGNING_RPC_ENDPOINT = 'https://node.testnet.like.co/rpc/';
config.NFT_COSMOS_DENOM = 'nanoekil';

config.LIKE_NFT_EVM_INDEXER_API = 'https://likenft-indexer.pandawork.com/api';
config.LIKE_NFT_EVM_INDEXER_API_KEY = '';

config.EVM_RPC_ENDPOINT_OVERRIDE = '';

config.LIKER_PLUS_PRODUCT_ID = '';
config.LIKER_PLUS_20_COUPON_ID = '';
config.LIKER_PLUS_MONTHLY_PRICE_ID = '';
config.LIKER_PLUS_YEARLY_PRICE_ID = '';
config.LIKER_PLUS_GIFT_MONTHLY_PRICE_ID = '';
config.LIKER_PLUS_GIFT_YEARLY_PRICE_ID = '';

config.ARWEAVE_LIKE_TARGET_ADDRESS = '';
config.ARWEAVE_EVM_TARGET_ADDRESS = '';
config.LIKE_PRICE_MULTIPLIER = 1;
config.IPFS_ENDPOINT = 'https://ipfs.infura.io:5001/api/v0';
config.REPLICA_IPFS_ENDPOINTS = [];
config.ARWEAVE_LINK_INTERNAL_TOKEN = '';

config.LIKER_NFT_TARGET_ADDRESS = '';

config.NFT_BOOK_LIKER_LAND_FEE_RATIO = 0.05;
config.NFT_BOOK_TIP_LIKER_LAND_FEE_RATIO = 0.10;
config.NFT_BOOK_LIKER_LAND_COMMISSION_RATIO = 0.3;
config.NFT_BOOK_LIKER_LAND_ART_FEE_RATIO = 0.1;

config.NFT_BOOK_FREE_CLASS_IDS = [];

config.LIKER_NFT_FIAT_MIN_RATIO = 0.01;

config.LIKER_NFT_SUBSCRIPTION_PRICE_ID = '';
config.LIKER_NFT_SUBSCRIPTION_MINT_SECRET = '';

config.LIKER_NFT_BOOK_GLOBAL_READONLY_MODERATOR_ADDRESSES = [];

config.NFT_BOOK_LISTING_NOTIFICATION_WEBHOOK = '';
config.NFT_BOOK_SALES_NOTIFICATION_WEBHOOK = '';
config.NFT_BOOK_SALES_INVALID_CHANNEL_ID_NOTIFICATION_WEBHOOK = '';
config.NFT_BOOK_SALES_OUT_OF_STOCK_NOTIFICATION_WEBHOOK = '';
config.PLUS_SUBSCRIPTION_NOTIFICATION_WEBHOOK = '';
config.NFT_BOOK_LIKER_LAND_ART_STRIPE_WALLET = '';
config.SLACK_OUT_OF_STOCK_NOTIFICATION_THRESHOLD = 5;

config.AUTHCORE_API_ENDPOINT = '';
config.AUTHCORE_PUBLIC_CERT_PATH = '';
config.AUTHCORE_PRIVATE_KEY_PATH = '';
config.AUTHCORE_SERVICE_ACCOUNT_ID = '';
config.AUTHCORE_SECRETD_STATIC_KEY = '';
config.AUTHCORE_WEB_HOOK_SECRET = '';

config.LIKECO_INTERNAL_API_ENDPOINT = '';
config.LIKECO_INTERNAL_API_KEY = '';

config.JWT_PUBLIC_CERT_PATH = '';
config.JWT_PRIVATE_KEY_PATH = '';
config.ECDSA_JWT_PUBLIC_CERT_PATH = '';
config.ECDSA_JWT_PRIVATE_KEY_PATH = '';
config.PROVIDER_JWT_COMMON_SECRET = '';

config.STRIPE_KEY = 'sk_test_51J1ZQvJ8'; // random dummy key
config.STRIPE_WEBHOOK_SECRET = '';

config.FB_PIXEL_ID = '';
config.FB_ACCESS_TOKEN = '';

config.INTERCOM_API_SECRET = '';
config.INTERCOM_ACCESS_TOKEN = process.env.INTERCOM_ACCESS_TOKEN || '';

config.MATTERS_APP_ID = '';
config.MATTERS_APP_SECRET = '';

config.SENDGRID_API_KEY = '';

config.REGISTER_LIMIT_WINDOW = 3600000; // 1hour
config.REGISTER_LIMIT_COUNT = 0; // 0 = disable
config.NEW_USER_BONUS_COOLDOWN = 259200000; // 3 days

config.GCLOUD_PUBSUB_MAX_MESSAGES = 10;
config.GCLOUD_PUBSUB_MAX_WAIT = 1000;
config.GCLOUD_PUBSUB_ENABLE = false;
config.APP_SERVER = 'likecoin-api-public';

config.GOOGLE_RETAIL_PROJECT_ID = '';

config.CMC_PRO_API_KEY = '';
config.CMC_API_CACHE_S = 300;

config.IS_CHAIN_UPGRADING = false;

config.LIKER_LAND_GET_WALLET_SECRET = '';

config.WNFT_BATCH_PURCHASE_LIMIT = 100;

config.AIRTABLE_API_KEY = process.env.AIRTABLE_API_KEY;
config.AIRTABLE_BASE_ID = '';

config.SLACK_COMMAND_TOKEN = '';

config.USER_ALLOWED_CHANNEL_IDS = '';
config.USER_ALLOWED_USER_IDS = '';
config.WALLET_ALLOWED_USER_IDS = '';
config.WALLET_ALLOWED_CHANNEL_IDS = '';
config.TEAM_WALLET_TABLE = {};
config.BOOK_ADMIN_ALLOWED_CHANNEL_IDS = '';
config.BOOK_ADMIN_ALLOWED_USER_IDS = '';

config.MAGIC_SECRET_API_KEY = process.env.MAGIC_SECRET_API_KEY;

module.exports = config;
